### ISSUE TITLE
建议加入自定义UI功能

### ISSUE THREAD

**Issue by RyzenLing** [OpenWebGAL/WebGAL#220]
虽然自带的UI很好，但是我还是想要自定义UI（），求求了呜

**Comment by KH-XXXVillager** [comment]
应该可以直接改css

**Comment by MakinoharaShoko** [comment]
请考虑学一些基础的HTML和CSS，然后可以修改项目源码
并且，今后的版本可能会支持一些UI自定义

**Comment by MakinoharaShoko** [comment]
我们已经开始计划自定义 UI 和在编辑器中编辑 UI 模板的功能了。具体来说，有以下关键工作：
1、关键 UI 模板化
2、建立模板配置文件和模板资源目录（game目录下）
3、编辑器支持模板编辑和从模版创建游戏
4、即使创建了游戏，也可以修改使用什么模板
