### ISSUE TITLE
Control option availability using variables

### ISSUE THREAD

**Issue by IdrilK** [OpenWebGAL/WebGAL#310]
choose:MaDescription:Chapter-2.txt:when=a>1|AutreDescription:Chapter-3.txt:when=a<1|... etc..;

This would allow limiting the number of choices on the screen or hiding certain choices.
(这将允许限制屏幕上的选择数量或隐藏某些选项。)

**Comment by MakinoharaShoko** [comment]
This is a good idea

**Comment by MakinoharaShoko** [comment]
#445
