### ISSUE TITLE
continue 参数的实现

### ISSUE THREAD

**Issue by MakinoharaShoko** [OpenWebGAL/WebGAL#374]
一个演出一般而言需要一定的时间。如果我们想要在演出结束后继续推进游戏怎么做？在之前的演出管理器中，我们已经为 `IPerform` 设置了一个字段，用于控制在演出结束后要不要继续执行下一条。但是这个字段暂时被废弃了，因为想要实现可能很困难，我们要考虑多个演出同时进行的情况。
理想的方式，莫过于在演出结束后（调用 `stopFunction`后）去检查是否所有演出都已经结束，如果结束，就继续推进游戏，就像我们在 `nextSentence` 中做的那样。
然而，我们还需要考虑像“保持演出”这样没有确定的结束时间的情况，以及像播放视频这样无法提前知道结束时间的情况。
是的，这个功能可能很复杂，因此只是放在这里，以供持续记录关于解决这个问题的灵感。

**Comment by JusticHentai** [comment]
最近在使用 webgal 做游戏也遇到了类似的问题，可以提供个灵感 ，这边做法是拆分 nextScene 代表一个场景和 nextSentence，nextScene 执行时候会 await 等待多个 nextSentence 执行完返回才可以执行下一次 nextScene，实现可以用迭代器的方式；演出结束 hook 可以在初始化时 new 一个 promise 并把它的 resolve 保存起来，让 nextScene 去 await 这个 promise，结束时调用 resolve，nextScene 就可以执行后续

**Comment by MakinoharaShoko** [comment]
https://github.com/OpenWebGAL/WebGAL/commit/86bb6089d75bea9e01267a9e77470366b2bbba01
