### ISSUE TITLE
Audio not playing on Chrome (Version: 118.0.5993.118)

### ISSUE THREAD

**Issue by generalfreed** [OpenWebGAL/WebGAL#392]
English:
I've published a website at [https://sekai.candypop.jp/webgal-jp.site/](https://sekai.candypop.jp/webgal-jp.site/). However, character voices aren't playing on Chrome (Version: 118.0.5993.118). They play without any issues when accessed from Firefox or when installed as a PWA from Chrome. Also, the voice files are in mp3 format and only use alphanumeric characters for filenames.

Could this be an issue with the `<audio>` tag not working properly on certain versions of Chrome? Would implementing with an iframe or some other method be advisable? Please provide guidance.

中文:
我在[https://sekai.candypop.jp/webgal-jp.site/](https://sekai.candypop.jp/webgal-jp.site/)发布了一个网站。但是，在Chrome (版本: 118.0.5993.118)上角色的声音无法播放。当从Firefox访问或从Chrome安装为PWA时，它们可以正常播放。另外，语音文件是mp3格式，文件名只使用字母数字字符。

这可能是`<audio>`标签在某些版本的Chrome上无法正常工作的问题吗？使用iframe或其他方法来实现会更好吗？请提供指导。

日本語:
こちらのサイト [https://sekai.candypop.jp/webgal-jp.site/](https://sekai.candypop.jp/webgal-jp.site/) を公開しましたが、Chrome (バージョン: 118.0.5993.118)でキャラクターのボイスが再生されません。FirefoxやChromeからPWAとしてインストールした場合には、問題なくボイスが再生されます。また、ボイスファイルはmp3形式で、ファイル名は半角英数字のみを使用しています。

この問題は、特定のChromeのバージョンで`<audio>`タグが正しく動作しないためでしょうか？iframeなどを使用して実装する方が良いのでしょうか？アドバイスをお願いします。

**Comment by MakinoharaShoko** [comment]
I have already seen this issue. However, at the moment, I don't have any ideas, but I will continue to try to troubleshoot.

**Comment by MakinoharaShoko** [comment]
I think there might be some issues with your audio files. I checked your website and found that some vocals, like the warning sound effect at the beginning of the game, are working fine. However, the voice recordings are not playing properly. But there is no difference in the code execution between them, so if one is working and the other is not, it could be a problem with the audio files.
Considering that your voice recordings might have been generated using different software, could you try transcoding the audio files to convert them into the correct format? The format irregularity might be causing the `oncanplay` callback to not execute properly.

**Comment by MakinoharaShoko** [comment]
After listening to feedback from other developers, I found that the inability to play the audio files may be related to them being placed in a subdirectory. Since this can be consistently reproduced in this way, I will proceed to fix it.

**Comment by MakinoharaShoko** [comment]
We are trying to change the dev branch to not use oncanplay to trigger playback. Please verify if voice playback works correctly after using this method.
https://github.com/OpenWebGAL/WebGAL/commit/7e481d7f9a91d6610b73eea15902ec4060ef8d9d

**Comment by generalfreed** [comment]
Thank you.
I tried deploying it on different sites, In my environment the voice was played.

**Render**
https://digigame-webgal.onrender.com/
**Heroku**
https://digigame-3904ed0f155e.herokuapp.com/
