### ISSUE TITLE
iOS端打开webgal demo时报错

### ISSUE THREAD

**Issue by shan-mx** [OpenWebGAL/WebGAL#428]
![WechatIMG2142](https://github.com/OpenWebGAL/WebGAL/assets/36291011/b9a5fb6c-0bfa-4242-9716-1b91e8db420f)
![WechatIMG2141](https://github.com/OpenWebGAL/WebGAL/assets/36291011/3dc5c311-cc22-4af0-a336-0e7414ea2c59)
如图，进入后在图2重复加载，直到展示图1界面

**Comment by MakinoharaShoko** [comment]
我使用 Mac OS 上的 Xcode 模拟器 Safari 调试网页，在最新版 iOS 下可以正常运行。但是我并没有实体机的 iPhone，所以我无法在实体机上调试。

**Comment by Max-Liu** [comment]
<img width="1795" alt="Screenshot 2024-01-23 at 08 48 43" src="https://github.com/OpenWebGAL/WebGAL/assets/1518955/8fdc4ffa-fb3d-4baf-ad1a-ae49683079e1">

我也出现了这个问题，看了下应该是手机端safari爆内存了 @MakinoharaShoko

**Comment by MakinoharaShoko** [comment]
> <img alt="Screenshot 2024-01-23 at 08 48 43" width="1795" src="https://private-user-images.githubusercontent.com/1518955/298771446-8fdc4ffa-fb3d-4baf-ad1a-ae49683079e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzE4NjUsIm5iZiI6MTcwNTk3MTU2NSwicGF0aCI6Ii8xNTE4OTU1LzI5ODc3MTQ0Ni04ZmRjNGZmYS1mYjNkLTRiYWYtYWQxYS1hZTQ5NjgzMDc5ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDA1OTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM0ZTA0NTE4ZDg3MjBkN2FiMTkwOWNhNDllYzc2Yjk1ZDZhNTIyMWY5ZTE3NjI3OTFlMDM2OThlNmFhMTZjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tmbLIKz1kf_PaPm6zVQ6jLTzBzJmEUTiOLmG6I5WCaw">
> 我也出现了这个问题，看了下应该是手机端safari爆内存了 @MakinoharaShoko

这看起来很奇怪......我使用 Chrome 调试，运行一个流程非常长（数小时）的游戏，并没有发现内存泄漏。

**Comment by MakinoharaShoko** [comment]
https://forum.cocos.org/t/topic/137672/32#:~:text=%E5%85%B6%E4%BB%96%E5%BC%95%E6%93%8E%E5%9C%A8wkwebview%E4%B8%8A%E8%B2%8C%E4%BC%BC%E4%B9%9F%E6%97%A0%E6%B3%95%E9%87%8A%E6%94%BE%E5%86%85%E5%AD%98%EF%BC%8C%E7%9C%8B%E6%9D%A5%E5%8F%AA%E8%83%BD%E5%87%8F%E5%B0%91%E6%B8%B8%E6%88%8F%E6%95%B4%E4%BD%93%E5%86%85%E5%AD%98%E6%B6%88%E8%80%97%EF%BC%8C%E7%9C%8B%E6%9D%A5%E6%98%AFIOS%20wkwebview%E6%9C%BA%E5%88%B6%E5%A6%82%E6%AD%A4%EF%BC%8C%E4%B8%8D%E9%80%82%E5%90%88%E8%B7%91%E4%B8%80%E4%BA%9B%E5%A4%A7%E5%9E%8B%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%8F%AA%E8%83%BD%E8%B7%91%E5%B0%8F%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%9C%A8%E6%9C%AC%E8%BA%AB%E5%86%85%E5%AD%98%E6%B6%88%E8%80%97%E5%B0%8F%E7%9A%84%E6%83%85%E5%86%B5%E4%B8%8B%20%E4%B8%8D%E9%87%8A%E6%94%BE%20%E4%B9%9F%E6%97%A0%E6%89%80%E8%B0%93%E4%BA%86%E3%80%82%E4%BD%8E%E7%AB%AF%E6%9C%BAiphone7%20%E8%BF%90%E8%A1%8C%E5%86%85%E5%AD%98%E5%8F%AA%E6%9C%892G%EF%BC%8Cwkwebview%E5%86%85%E5%AD%98%E4%B8%8D%E9%87%8A%E6%94%BE%E8%BE%BE%E5%88%B01G%E6%97%B6%E5%80%99%20%E5%B0%B1%E4%BC%9Acrash%EF%BC%8C%E9%AB%98%E7%AB%AF%E6%9C%BA%E5%86%85%E5%AD%98%E5%A4%A7%E4%B9%9F%E8%83%BD%E8%B7%91

合理怀疑是 Safari 有 Bug，翻到一个帖子说 Cocos 2D 在 Safari 上也有崩溃现象

**Comment by MakinoharaShoko** [comment]
再及：我使用我的安卓手机和 PC 调试，并没有检测到内存泄漏的现象。在 Mac 版 Safari 下也可以正常运行。合理怀疑是 Mobile Safari 在打开高负载网站时由于性能问题无法正常运行。我在 Mac Xcode 中使用 iOS 模拟器运行，可以正常运行，可能是因为 Mac 本身性能较好。先前也有找过使用 iPhone 的用户测试，经反馈除了不能使用强制旋转的方式来适配横屏外，也是可以正常打开的。我认为这可能是个很难排查的故障，因为除了 Safari，在其他任何浏览器上表现的都非常正常。

**Comment by shan-mx** [comment]
> 再及：我使用我的安卓手机和 PC 调试，并没有检测到内存泄漏的现象。在 Mac 版 Safari 下也可以正常运行。合理怀疑是 Mobile Safari 在打开高负载网站时由于性能问题无法正常运行。我在 Mac Xcode 中使用 iOS 模拟器运行，可以正常运行，可能是因为 Mac 本身性能较好。先前也有找过使用 iPhone 的用户测试，经反馈除了不能使用强制旋转的方式来适配横屏外，也是可以正常打开的。我认为这可能是个很难排查的故障，因为除了 Safari，在其他任何浏览器上表现的都非常正常。

可能不仅是Safari的问题，我在iPhone 12 Pro Max以及iPhone 13上尝试使用Chrome打开demo.openwebgal.com，都遇到了无法打开网页的现象，希望可以再排查下对于iOS的性能适配情况

**Comment by MakinoharaShoko** [comment]
https://github.com/pixijs/pixijs/issues/8133
https://github.com/pixijs/pixijs/issues/9676
https://developer.apple.com/forums/thread/737042

以上是一些相关的链接，我认为可能是由于我们使用的依赖库——PixiJS 在 iOS 上遇到了一些问题。但是在有使用 iPhone 的开发者加入我们的项目团队之前，暂时没有解决这个问题的物质条件。

**Comment by MakinoharaShoko** [comment]
@Max-Liu @shan-mx 
https://demo-dev.openwebgal.com/
我应用了一些修改在 iPhone 设备上，停止了在 iPhone 设备上使用我写的自动适配屏幕缩放，也许可以运行。
自动屏幕缩放旨在将 WebGAL 的渲染区域缩放以适配屏幕长宽。但是在 iPhone 上，可能引发了一些 WebGL 性能问题。我在 iPhone 上关闭了这一功能，现在应当可以运行。

**Comment by Max-Liu** [comment]
> @Max-Liu @shan-mx https://demo-dev.openwebgal.com/ 我应用了一些修改在 iPhone 设备上，停止了在 iPhone 设备上使用我写的自动适配屏幕缩放，也许可以运行。 自动屏幕缩放旨在将 WebGAL 的渲染区域缩放以适配屏幕长宽。但是在 iPhone 上，可能引发了一些 WebGL 性能问题。我在 iPhone 上关闭了这一功能，现在应当可以运行。

确实没有再崩溃了，但是对话和首页菜单中的文字都变粗了很多
![IMG_9921](https://github.com/OpenWebGAL/WebGAL/assets/1518955/a09d457d-fcf4-4da3-928a-0984c5cc7116)
![Uploading IMG_9922.PNG…]()

**Comment by MakinoharaShoko** [comment]
> > @Max-Liu @shan-mx https://demo-dev.openwebgal.com/ 我应用了一些修改在 iPhone 设备上，停止了在 iPhone 设备上使用我写的自动适配屏幕缩放，也许可以运行。 自动屏幕缩放旨在将 WebGAL 的渲染区域缩放以适配屏幕长宽。但是在 iPhone 上，可能引发了一些 WebGL 性能问题。我在 iPhone 上关闭了这一功能，现在应当可以运行。
> 
> 确实没有再崩溃了，但是对话和首页菜单中的文字都变粗了很多 ![IMG_9921](https://private-user-images.githubusercontent.com/1518955/301068320-a09d457d-fcf4-4da3-928a-0984c5cc7116.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTUxMzcsIm5iZiI6MTcwNjY5NDgzNywicGF0aCI6Ii8xNTE4OTU1LzMwMTA2ODMyMC1hMDlkNDU3ZC1mY2Y0LTRkYTMtOTI4YS0wOTg0YzVjYzcxMTYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDk1MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFjZTI1OThkMDQzYTExOGE2ODVhZWM4NDNjNDdhZTIzNTgyYmIxMzI0ZWZlMjdmNTU1M2UxMmQzN2Q4ODJmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ySy8kcaaZtPdocoOm-UMBU_sVCug1twKtK-QIHlL--g) ![IMG_9922](https://private-user-images.githubusercontent.com/1518955/301069614-8f4c4041-d476-4c7c-9e93-c71db5bc81bf.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTUxMzcsIm5iZiI6MTcwNjY5NDgzNywicGF0aCI6Ii8xNTE4OTU1LzMwMTA2OTYxNC04ZjRjNDA0MS1kNDc2LTRjN2MtOWU5My1jNzFkYjViYzgxYmYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDk1MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjJjZjliMWY5YzAyYzQ4OWQ2NTk2MGE0MjE5YTEwNDI2ZmFkNWY0ZTgyNWNhZjU0MjMyODg0ZmZlMTA3N2JlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ydb350gzUaRQF78frZ9HfE7T0H40Rrc1N_8kxr8VaPo)

可能是由于不应用缩放导致的。不过从基本使用上来看，总体问题已经不大，我们后面再逐步优化这些问题。
此 Issue 只用于解决崩溃问题，样式不正确的问题，请额外提 Issue。
我即将关闭这个 Issue，如果再次发现崩溃问题，请 Reopen

**Comment by shan-mx** [comment]
@MakinoharaShoko 感谢您的工作！我会为样式问题提个issue
