### ISSUE TITLE
在 dev 分支上，测试 bgm 功能是否正常

### ISSUE THREAD

**Issue by MakinoharaShoko** [OpenWebGAL/WebGAL#429]
添加 bgm
关闭 bgm
切换 bgm
添加后立即关闭 bgm（连续执行）
关闭后立即添加 bgm（连续执行）
添加后隔几个语句关闭 bgm
关闭后隔几个语句添加 bgm

**Comment by unlimitedcodeG** [comment]
Test is Ready Go

**Comment by MakinoharaShoko** [comment]
> Test is Ready Go

忘了提到了，以上的测试项目也要考虑bgm渐入的情况
