### ISSUE TITLE
在没有文本框且设置了自动隐藏操作按钮时，按钮一直无法显示

### ISSUE THREAD

**Issue by MakinoharaShoko** [OpenWebGAL/WebGAL#433]

**Comment by MakinoharaShoko** [comment]
@tinyAdapter

**Comment by tinyAdapter** [comment]
会有一直不显示文本框的时候么？
Anyway，感觉在没有文本框的时候应该用另一套逻辑：鼠标移动显示，鼠标停止移动一段时间后隐藏
我看看怎么搞

**Comment by MakinoharaShoko** [comment]
> 会有一直不显示文本框的时候么？ Anyway，感觉在没有文本框的时候应该用另一套逻辑：鼠标移动显示，鼠标停止移动一段时间后隐藏 我看看怎么搞

是的，因为脚本里面可以把对话框隐藏了，在做一些全屏演出的时候会很好用。我认为在没有文本框的时候按你说的逻辑很合适。
