### ISSUE TITLE
角色名字未做明确的字数限制，导致超出文本框。

### ISSUE THREAD

**Issue by unlimitedcodeG** [OpenWebGAL/WebGAL#436]
![image](https://github.com/OpenWebGAL/WebGAL/assets/48639567/95b4a094-631b-4e4f-877c-d357f5ebeaf8)

**Comment by MakinoharaShoko** [comment]
该问题属于用户自发行为。如果他们这样做，就不要为产生问题感到震惊。

**Comment by unlimitedcodeG** [comment]
> 该问题属于用户自发行为。如果他们这样做，就不要为产生问题感到震惊。

理性讨论 从软件设计上，我们应该是不允许用户出现这种操作的，从根本上消除问题，虽然可能会带有成本，从测试角度，也对我们的边界值进行了一个探测。
