### ISSUE TITLE
同时执行多条命令

### ISSUE THREAD

**Issue by XianWeiGP-R** [OpenWebGAL/WebGAL#448]
由于webgal引擎是并行执行，由上到下逐步执行命令。这就局限了某些表现。
例如：不能同时播放语音，不能立绘同时平移，等等。按顺序执行的话效果会很滑稽，而-next只是加快了衔接，并不能完全等同于同时播放。
希望能够增加一个新的命令，以达到同时播放的效果。

建议：新的命令不需要大动干戈，只需要在预加载时统计一下有几个，有没有连续的。有≧2个连续的新命令后，便将这几行视为一个同时执行的块，一执行到那一行，整个块都同时执行。
如果只有一行，这个命令便不生效，因为没有需要同时执行的目标。

**Comment by MakinoharaShoko** [comment]
https://github.com/OpenWebGAL/WebGAL/blob/426d1ea1ff4b12afd74c15dde0700ede97d3b7c5/packages/webgal/src/Core/controller/gamePlay/scriptExecutor.ts#L126C3-L130C4

被 next 连接的语句在引擎中事实上是同步执行的，因此，被 next 参数连接的语句就已经可以达到你的目标。

**Comment by MakinoharaShoko** [comment]
https://github.com/OpenWebGAL/WebGAL/assets/30483415/765dff63-3873-4f6e-a65e-55c95320df1b
