### ISSUE TITLE
支持指令中选择UI样式

### ISSUE THREAD

**Issue by hundun000** [OpenWebGAL/WebGAL#452]
基于 #220 ，支持进一步定义多种子样式，然后指令中可选择UI样式。使用场景例如：

- 不同角色say时，对话框样式不同
- 用特定对话框样式表示内心独白的say

指令例如：

> say:我的内心独白 -subStyle=1;

**Comment by MakinoharaShoko** [comment]
https://github.com/OpenWebGAL/WebGAL/pull/473/commits/fab85320277503160c067cb8954650d082686a52
