### ISSUE TITLE
iOS端运行WebGAL时出现样式问题

### ISSUE THREAD

**Issue by shan-mx** [OpenWebGAL/WebGAL#459]
iOS端运行https://demo-dev.openwebgal.com/ 时出现样式问题：
1. 页面长宽未能占满浏览器
2. 字体出现变粗/重影现象
![image](https://github.com/OpenWebGAL/WebGAL/assets/36291011/f7cfeadf-1953-40ae-8294-bf0b35cb8f2a)
![image](https://github.com/OpenWebGAL/WebGAL/assets/36291011/29c04fd8-0a79-4587-a52b-533d47a080aa)

**Comment by MakinoharaShoko** [comment]
关于 iOS 样式问题的报告：
1、该问题是由于 Safari 限制了我们使用在其他设备上应用的自动缩放调整代码。因此我们无法强制缩放整个 APP，只能使用一个较低的初始缩放（0.2）来避免显示不完全。iOS 用户如需调整缩放，需要自行使用双指手势操作。
2、是由于 Safari 无法正常渲染粗体文字导致，我们验证了是 Safari 渲染的一个 bug，具体请参考我们附件中的录屏。对于这个问题，我们将在下版本开始实施 UI 自定义的功能。如果你要发布的游戏有在 Safari 上运行的需求，请使用 UI 自定义功能将所有粗体文本样式修改为常规样式。

附件：

https://github.com/OpenWebGAL/WebGAL/assets/30483415/1db9b408-ccf5-4d24-9c9d-fb997c1a4f2b

**Comment by MakinoharaShoko** [comment]
通过关闭合成字体，解决了 iOS 上字体出现重影的问题。该问题确实是 Safari 的一个 bug
https://www.reddit.com/r/Safari/comments/17sa9w9/safari_you_are_killing_me_with_the_700_font/
之后为彻底解决字体问题，将在 iOS 设备上单独加载字体库的加粗版本，而不是使用任何合成字体。
