### ISSUE TITLE
建议增加多图层堆叠的支持

### ISSUE THREAD

**Issue by ResonaAlbert** [OpenWebGAL/WebGAL#468]
希望能够增加添加额外的图片在人物与背景涂层之间，或者人物图层之上，用来实现更加复杂的特效演出效果或者临时显示小物件等

**Comment by MakinoharaShoko** [comment]
你可以尝试用设置 id 的方式，通过设置多个立绘来实现类似的效果。
立绘堆叠的优先级是根据先后顺序确定的。在设置了id的情况下，立绘理论上可以堆叠很多。如果你需要再人物和背景之间显示图像，可以先设置图像后设置立绘，立绘会出现在图像上面。反之亦然。

**Comment by MakinoharaShoko** [comment]
我们将考虑允许用户通过脚本方式设置某个 id 的立绘的 z-index

**Comment by MakinoharaShoko** [comment]
https://github.com/OpenWebGAL/WebGAL/commit/6eea82fa3b9d81cbbf32f83d2fd6d930e32872a8
