### ISSUE TITLE
Feature Asking: Add multiple conditions support for condition execution (-when)

### ISSUE THREAD

**Issue by GarinZ** [OpenWebGAL/WebGAL#475]
In our platform, users want to create more complex game with multiple variables compositing conditions.

Example:
```
setVar: appearance = 0;
setVar: fitness = 0;
; //  ... some var changes sentences.

changScene: startStarCareer.txt   -when=appearance>10&&fitness>10;
```

We need support for this feature

**Comment by MakinoharaShoko** [comment]
https://github.com/OpenWebGAL/WebGAL/commit/fb4ef202cfd80d24591c0220ca385f86551b9213
