### ISSUE TITLE
建议将脚本后缀改为webgal特有的后缀

### ISSUE THREAD

**Issue by xiaoxustudio** [OpenWebGAL/WebGAL#483]
虽然这个无关紧要，但考虑后面有更多开发者的加入，或者是以后会出现的自定义ui文件，我还是认为可以将现有的脚本后缀名`.txt`更改成其他的后缀名，这样也更有辨识度。

**Comment by MakinoharaShoko** [comment]
这个问题是一个非常庞大的历史遗留问题。由于引擎、编辑器、文档中有大量的有关后缀名是 `.txt` 的代码或陈述，修改脚本后缀名可能带来的风险太大了，因此，在更新的下一个大版本（版本号第一位变更）前，没有计划修改 WebGAL 脚本的后缀名。
