### ISSUE TITLE
【新功能请求】可选的非强制横屏---就是手机端竖屏

### ISSUE THREAD

**Issue by AIsht669** [OpenWebGAL/WebGAL#567]
能否取消强制横屏. 
以及下方回想存档等功能的自定义显示( 显示/隐藏/ 只显示小图标 )

**Comment by MakinoharaShoko** [comment]
第二个需求可以加入开发计划。第一个需求可能无法实现，因为我们的 UI 是基于横屏设计的。

**Comment by AIsht669** [comment]
> 第二个需求可以加入开发计划。第一个需求可能无法实现，因为我们的 UI 是基于横屏设计的。

感谢, 我翻看了一下模板貌似也没办法修改.
第一个需求貌似才是目标.不过算了.感谢. 
第二个需求我倒是通过js修改了
